WebApp/ViewModels/Lab4ViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web.SessionState;
using WebApp.Helpers;
using Raven.Client;
using Raven.Json.Linq;
using WebApp.Models;

namespace WebApp.ViewModels
{
	public class Lab4ViewModel
	{
		/// <summary>
		/// Gets or sets the calculated value.
		/// </summary>
		/// <value>
		/// The calculated value.
		/// </value>
		[Required]
		[Display(Name = "Value")]
		[RegularExpression(@"[0-9]+", ErrorMessage = "{0} must be a Number.")]
		public string CalculatedValue { get; set; }

		public string SessionTimeOut { get; set; } 
		public LimitedQueue<string> RunningCalculations { get; set; }
		public decimal RunningTotal { get; set; }
	}
}

WebApp/ViewModels/Lab5ViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Web.SessionState;
using WebApp.Helpers;
using Raven.Client;
using Raven.Json.Linq;
using WebApp.Models;

namespace WebApp.ViewModels
{
	public class Lab5ViewModel
	{
		public int ID { get; set; }

		/// <summary>
		/// Gets or sets the Stock Symbol value.
		/// </summary>
		/// <value>
		/// The Stock Symbol value.
		/// </value>
		[Required]
		[Display(Name = "Stock Symbol")]
		[StringLength(20, ErrorMessage = "{0} must be between {2} and {1} characters long.", MinimumLength = 1)]
		//[RegularExpression(@"([A-Z]{1,4})", ErrorMessage = "Not in correct format for a Stock Symbol.")]
		public string StockSymbol { get; set; }

		public string StockSummary { get; set; }

		public string StockChart { get; set; }

		public DateTime LastUpdated { get; set; }

		private int m_RefreshInterval = 1;

		public int RefreshInterval
		{
			get { return m_RefreshInterval; }
			set { m_RefreshInterval = value; }
		}

	}
}

WebApp/ViewModels/Lab7ViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebApp.Models;

namespace WebApp.ViewModels
{
	public class Lab7ViewModel
	{
		public List<Course> Courses { get; set; }
	}
}		

WebApp/Controllers/LabsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApp.Models;
using WebApp.Helpers;
using WebApp.ViewModels;
using Omu.ValueInjecter;
using System.Net;
using System.IO;
using System.Net.Cache;
using RestSharp;
using HtmlAgilityPack;
using WebApp.Models.CourseListing;

namespace WebApp.Controllers
{
	public class LabsController : RavenController
    {
		//
		// POST: /Labs/LabMain
		public ActionResult LabMain()
		{
			return View();
		}

		//
		// POST: /Labs/Lab3
		public ActionResult Lab3()
        {
            return View();
        }

		[HttpPost]
		[AllowAnonymous]
		[ValidateAntiForgeryToken]
		public ActionResult Lab3(LabModels model)
		{
			if(string.IsNullOrEmpty(model.UserID) && string.IsNullOrEmpty(model.UserName))
			{
				return View();
			}
			else
			{
				return View(model);
			}

			
			//return PartialView("_ModulusSumPartial", model);
		}

		//
		// POST: /Labs/Lab4
		public ActionResult Lab4()
		{
			Lab4DataAccess dataAccess = new Lab4DataAccess(RavenSession);
			PrintingCalculator item = dataAccess.RetrieveFromSession();
			Lab4ViewModel model = new Lab4ViewModel();

			if(item != null)
			{
				model.InjectFrom(item);
			}

			return View("Lab4", model);
		}
		
		[HttpPost]
		[AllowAnonymous]
		//[ValidateAntiForgeryToken]
		public ActionResult Lab4(string add, string subtract, string multiply, string divide, string clearmemory, string execute, Lab4ViewModel model)
		{			
			int value = 0;
			Lab4DataAccess dataAccess = new Lab4DataAccess(RavenSession);
			PrintingCalculator item = dataAccess.RetrieveFromSession();
			
			if(!string.IsNullOrEmpty(model.CalculatedValue) && int.TryParse(model.CalculatedValue, out value))
			{
				if(!string.IsNullOrEmpty(add))
				{
					item.Add(value);
				}
				else if(!string.IsNullOrEmpty(subtract))
				{
					item.Subtract(value);
				}
				else if(!string.IsNullOrEmpty(multiply))
				{
					item.Multiply(value);
				}
				else if(!string.IsNullOrEmpty(divide))
				{
					item.Divide(value);
				}

				//Save to store
				RavenSession.Store(item);
				RavenSession.SaveChanges();

				//Map changes to model
				model.InjectFrom(item);

				ModelState.Remove("CalculatedValue");
				model.CalculatedValue = string.Empty;
			}
			else
			{
				if(!string.IsNullOrEmpty(clearmemory))
				{
					ModelState.Clear();
					ModelState.Remove("CalculatedValue");
					model.CalculatedValue = string.Empty;

					dataAccess.ClearFromSession();

					//Clear Model
					model = new Lab4ViewModel();
				}
				else if(!string.IsNullOrEmpty(execute))
				{
					ModelState.Clear();
					ModelState.Remove("CalculatedValue");
					model.CalculatedValue = string.Empty;
				}
				else
				{
					//Map changes to model
					model.InjectFrom(item);
				}
			}

			return View("Lab4", model);
		}

		//
		// POST: /Labs/Lab5
		public ActionResult Lab5()
		{
			Lab5DataAccess dataAccess = new Lab5DataAccess(RavenSession);
			Lab5ViewModel model = dataAccess.RetrieveFromSession();

			return View("Lab5", model);
		}

		[HttpPost]
		[AllowAnonymous]
		//[ValidateAntiForgeryToken]
		public ActionResult Lab5(Lab5ViewModel model)
		{
			string chartSrc = string.Format("http://ichart.finance.yahoo.com/{0}={1}", "b?s", model.StockSymbol);
			string url = string.Format("http://finance.yahoo.com/q/cp?s={0}&ql=1", model.StockSymbol);
			HttpWebRequest httpWebRequest = (HttpWebRequest)WebRequest.Create(url);
			httpWebRequest.Method = "GET";
			httpWebRequest.CachePolicy = new RequestCachePolicy(RequestCacheLevel.NoCacheNoStore);
        
			//httpWebRequest.ContentType = "application/x-www-form-urlencoded";

			HttpWebResponse httpWebResponse = (HttpWebResponse)httpWebRequest.GetResponse();
			Stream responseStream = httpWebResponse.GetResponseStream();
			StreamReader streamReader = new StreamReader(responseStream);
			string response = streamReader.ReadToEnd();

			string start = @"<div class=""rtq_leaf"">";
			string end = @"<div id=""yfi_toolbox_mini_rtq"">";

			int startIndex = response.IndexOf(start);
			int endIndex = response.IndexOf(end);

			if(startIndex > 0 && endIndex > 0 && (endIndex > startIndex))
			{
				string stockSummaryHTML = response.Substring(startIndex, endIndex - startIndex);
				stockSummaryHTML = stockSummaryHTML + @"</div></div></div></div>";

				model.StockSummary = stockSummaryHTML;
				model.StockChart = chartSrc;
				model.LastUpdated = DateTime.Now;

				//Save the information
				Lab5DataAccess dataAccess = new Lab5DataAccess(RavenSession);
				Lab5ViewModel lab5Model = dataAccess.RetrieveFromSession();
				lab5Model.InjectFrom(model);
			}
			else
			{
				using(StringWriter sw = new StringWriter())
				{
					ViewEngineResult viewResult = ViewEngines.Engines.FindPartialView(ControllerContext, "_StockSummaryPartial");
					ViewContext viewContext = new ViewContext(ControllerContext, viewResult.View, ViewData, TempData, sw);
					viewResult.View.Render(viewContext, sw);

					model.StockSummary = sw.GetStringBuilder().ToString();
				}
			}

			return View("Lab5", model);
		}

		//
		// POST: /Labs/Lab6
		public ActionResult Lab6()
		{			
			return View("Lab6", null);
		}

		public ActionResult Lab7()
		{
			Lab7ViewModel model = new Lab7ViewModel();
			RestClientSettings settings = new RestClientSettings();

			settings.URL = "http://www3.mnsu.edu/courses/selectform.asp";
			settings.Method = Method.POST;

			//add valid header for kicks although they are not looking for it
			settings.Parameters.Add(new Parameter() { Name = "Accept", Value = "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", Type = ParameterType.HttpHeader });
			settings.Parameters.Add(new Parameter() { Name = "Accept-Encoding", Value = "gzip, deflate", Type = ParameterType.HttpHeader });
			settings.Parameters.Add(new Parameter() { Name = "Accept-Language", Value = "en-US,en;q=0.5", Type = ParameterType.HttpHeader });
			settings.Parameters.Add(new Parameter() { Name = "Host", Value = "www3.mnsu.edu", Type = ParameterType.HttpHeader });
			settings.Parameters.Add(new Parameter() { Name = "Referer", Value = "http://www3.mnsu.edu/courses/", Type = ParameterType.HttpHeader });
			settings.Parameters.Add(new Parameter() { Name = "User-Agent", Value = "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:19.0) Gecko/20100101 Firefox/19.0", Type = ParameterType.HttpHeader });

			// adds to POST or URL query string based on Method
			settings.Parameters.Add(new Parameter() { Name = "All", Value = "All Sections", Type = ParameterType.GetOrPost });
			settings.Parameters.Add(new Parameter() { Name = "campus", Value = "1,2,3,4,5,6,7,9,A,B,C,I,L,M,N,P,Q,R,S,T,W,U,V,X,Z", Type = ParameterType.GetOrPost });
			settings.Parameters.Add(new Parameter() { Name = "college", Value = "", Type = ParameterType.GetOrPost });
			settings.Parameters.Add(new Parameter() { Name = "courseid", Value = "", Type = ParameterType.GetOrPost });
			settings.Parameters.Add(new Parameter() { Name = "courselevel", Value = "", Type = ParameterType.GetOrPost });
			settings.Parameters.Add(new Parameter() { Name = "coursenum", Value = "", Type = ParameterType.GetOrPost });
			settings.Parameters.Add(new Parameter() { Name = "days", Value = "ALL", Type = ParameterType.GetOrPost });
			settings.Parameters.Add(new Parameter() { Name = "endTime", Value = "2359", Type = ParameterType.GetOrPost });
			settings.Parameters.Add(new Parameter() { Name = "semester", Value = "20143Fall 2013", Type = ParameterType.GetOrPost });
			settings.Parameters.Add(new Parameter() { Name = "startTime", Value = "0600", Type = ParameterType.GetOrPost });
			settings.Parameters.Add(new Parameter() { Name = "subject", Value = "CS", Type = ParameterType.GetOrPost });

			string content = CommonFunctions.MakeRestSharpRequest(settings);

			HtmlDocument doc = new HtmlDocument();
			doc.LoadHtml(content);

			HtmlNodeCollection htmlNodes = doc.DocumentNode.SelectNodes("//table[2]/tr");

			Course course = null;
			Section section = null;
			List<Course> courses = new List<Course>();
			bool readAdditionalInfo = false;
			foreach(HtmlNode node in htmlNodes)
			{
				if(node.NodeType == HtmlNodeType.Element && node.HasAttributes && node.Attributes["bgcolor"].Value == "#DFE4FF")
				{
					//Add previously collected course information
					if(course != null)
					{
						course.Sections.Add(section);
						courses.Add(course);
						readAdditionalInfo = false;
					}

					course = new Course();
					section = new Section();
					readAdditionalInfo = true;

					string[] value = node.InnerText.Trim().Replace("&nbsp;", string.Empty).Split(new string[] { "\r\n\t\t\t" }, StringSplitOptions.RemoveEmptyEntries);

					if(value != null && value.Length == 3)
					{
						//Department
						course.DepartmentID = value[0].Trim().Replace(@"&nbsp", string.Empty);

						//courseID and Name
						string[] courseIDandName = value[1].Split(new string[] { "&#150;" }, StringSplitOptions.None);
						course.CourseNumber = courseIDandName[0].Trim();
						course.CourseName = courseIDandName[1].Trim();

						//Number of credits
						course.Credits = value[2].Replace("(", string.Empty).Replace(" Credits)", string.Empty).Trim();
					}
				}
				else if(readAdditionalInfo && node.NodeType == HtmlNodeType.Element && node.HasAttributes && (node.Attributes["bgcolor"].Value == "#E1E1CC" || node.Attributes["bgcolor"].Value == "#FFFFFF"))
				{
					//Read Additional information
					int currentCell = 1;

					HtmlNodeCollection htmlTDNodes = node.SelectNodes("td");
										
					foreach(HtmlNode tdNode in htmlTDNodes)
					{
						if(tdNode.NodeType == HtmlNodeType.Element && tdNode.HasAttributes)
						{
							//Check if there is colspan skipping data blocks
							if(tdNode.Attributes["colspan"] != null && !string.IsNullOrEmpty(tdNode.Attributes["colspan"].Value))
							{
								int columnsSkipped = 0;
								int.TryParse(tdNode.Attributes["colspan"].Value, out columnsSkipped);

WebApp/Views/Labs/Lab3.cshtml
@model WebApp.Models.LabModels

@{
	ViewBag.Title = "Lab3 - AJAX & Java Script";
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
	@Scripts.Render("~/bundles/custom")
}

<hgroup class="title">
    <h1>@ViewBag.Title</h1>
</hgroup>

<section id="loginForm">
@using(Html.BeginForm())
{
	@Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

	<fieldset>
        <legend>User Name and User ID</legend>
        <ol>
            <li>
                <div class="control-group">
                    @Html.LabelFor(m => m.UserName)
                    @Html.TextBoxFor(m => m.UserName)
                    @Html.ValidationMessageFor(m => m.UserName)
                </div>
            </li>
            <li>
                <div class="control-group">
                    @Html.LabelFor(m => m.UserID)
                    @Html.TextBoxFor(m => m.UserID)
                    @Html.ValidationMessageFor(m => m.UserID)
                </div>
            </li>            
        </ol>
        <input type="submit" value="Calculate Modulus" class="btn btn-primary" />
    </fieldset>
}
</section>

@Html.Partial("_ModulusSumPartial", Model)

WebApp/Views/Labs/Lab4.cshtml
@model WebApp.ViewModels.Lab4ViewModel

@{
	ViewBag.Title = "Lab4 – Server Side";
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/custom/lab4")
}

<hgroup class="title">
    <h1>@ViewBag.Title</h1>
</hgroup>

<section id="loginForm">
	@using(Html.BeginForm())
	{
		@Html.AntiForgeryToken()
		@Html.ValidationSummary(true)
		        
        <table>
            <tr>
                <td  colspan="4">
                    @Html.ValidationMessageFor(m => m.CalculatedValue)
                </td>
            </tr>
            <tr>
                <td colspan="4">                    
                    @Html.TextBoxFor(m => m.CalculatedValue, new { @autocomplete = "off" })
                </td>
            </tr>        
            <tr>
                <td><input type="submit" name="add" id="add" value="+" style="width:60px;" /></td>
                <td><input type="submit" name="subtract" id="subtract" value="-" style="width:60px;" /></td>
                <td><input type="submit" name="multiply" id="multiply" value="X" style="width:60px;" /></td>
                <td><input type="submit" name="divide" id="divide" value="/" style="width:60px;" /></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td><input type="submit" name="clearmemory" id="clearmemory" value="C" class="cancel" style="width:60px;" /></td>
                <td><input type="submit" name="execute" id="execute" value="=" class="cancel" style="width:60px;" /></td>
            </tr>
        </table>
    }
</section>

@Html.Partial("_PrintingCalculatorPartial", Model)

WebApp/Views/Labs/Lab5.cshtml
@model WebApp.ViewModels.Lab5ViewModel
@{
    ViewBag.Title = "Lab5 – Pulling Stock Data";
}

@section styles{
	@Styles.Render("~/lab5/css")
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/custom/lab5")
}
<hgroup class="title">
    <h1>@ViewBag.Title</h1>
</hgroup>
<section>
	@using(Html.BeginForm("Lab5", "Labs", FormMethod.Post, new { Id = "Lab5Form" }))
    {
		@Html.AntiForgeryToken()
		@Html.ValidationSummary(true)
		        
        <table style="margin-left:auto; margin-right:auto;">
            <tr>
                <td>                    
                    <h3>Search Stock Symbol</h3>
                    <br />
                    @Html.ValidationMessageFor(m => m.StockSymbol) 
                </td>
            </tr>
            <tr>
                <td>                    
                    @Html.TextBoxFor(m => m.StockSymbol, new { @style = "width:150px;" })
                    <input type="submit" name="StockSearch" id="StockSearch" value="Get Quote" style="margin-left:20px;" />
                </td>
            </tr>           
            <tr>
                <td>
                    @if(Model != null && !string.IsNullOrEmpty(Model.StockSummary))
                    { 
                        @Html.Raw(Model.StockSummary)
                    }
                </td>
            </tr>
            <tr>
                <td>
                    @if(Model != null && !string.IsNullOrEmpty(Model.StockChart))
                    { 
                        <img style="margin-top:10px; margin-left:-2px;" src="@Model.StockChart" alt="Chart forYahoo! Inc. (YHOO)" border="0" height="250" width="500">
                    }
                </td>
            </tr>
             <tr>
                <td>                    
                    <div style="float:left; text-align:left;">
                        <span style="font-weight:bold;">Refresh:</span>
                        <select id="RefreshInterval" name="RefreshInterval" style="font-weight:bold; color:Green;">
                            <option value="1">1 min</option>
                            <option value="3">3 min</option>
                            <option value="5">5 min</option>
                            <option value="15">15 min</option>
                            <option value="60">1 hrs</option>
                            <option value="120">2 hrs</option>
                        </select>
                        <p>Last updated: <span style="font-weight:bold;">@Model.LastUpdated.ToString("yyyy/MM/dd HH:mm:ss")</span></p>
                        <input type="hidden" id="RefreshIntervalValue" name="RefreshIntervalValue" value="@Model.RefreshInterval">
                    </div>
                </td>
            </tr>
        </table>
    }  
</section>

WebApp/Views/Labs/Lab6.cshtml
@{
    ViewBag.Title = "Lab6";
    Layout = "~/Views/Shared/_Layout_Lab6.cshtml";
}

<div style="float:right; text-align:right; padding-top:40px;">
    @*<span style="font-weight:bold;">Refresh:</span>*@
    <select id="RefreshInterval" name="RefreshInterval" style="font-weight:bold; color:Green;">   
        <option value="1">1 min</option>
        <option value="3">3 min</option>
        <option value="5">5 min</option>
        <option value="15">15 min</option>
        <option value="60">1 hrs</option>
        <option value="120">2 hrs</option>
    </select>
    @*<input type="submit" id="Refresh" name="Refresh">
    <input type="hidden" id="RefreshIntervalValue" name="RefreshIntervalValue" value="1">
    <input type="hidden" id="count" name="count" value="1">*@
</div>
<br />

<h1>Overview</h1>
<p>Implement a small series of web pages which demonstrate your ability to render the same text under different cascading style sheets (CSS) formats. You must implement at least 3 different CSS styles, one of those styles should be clearly for on-screen viewing while another style should be clearly for printing.</p>

<h2>Bonus Points</h2>
<p>See scoring rubric above for the description of the feature needed.</p>

<h3>Deliverables</h3>
<p>Show your work to Dr. V or upload a short (1-3 minute) video to D2L (or just post the link to the video on D2L) demonstrating your working web site and the code that powers it. Alternatively, you can schedule a short (10-minute) in-person presentation with Dr. V by going to http://drchrisveltsos.youcanbookme.com/ </p>

WebApp/Views/Labs/Lab7.cshtml
@using WebApp.Models.CourseListing
@model WebApp.ViewModels.Lab7ViewModel

@{
    ViewBag.Title = "MSU IT Course Listings";
}

@section styles{
	@Styles.Render("~/Content/datatable")
}

@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/dataTables")
    @Scripts.Render("~/bundles/custom/lab7")
}

<hgroup class="title">
    <h1>@ViewBag.Title</h1>
</hgroup>

<section>
    @using(Html.BeginForm("Lab7", "Labs", FormMethod.Post, new { Id = "Lab7Form" }))
    {
        @Html.AntiForgeryToken()
		@Html.ValidationSummary(true)

        <table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered table-hover" id="course_listing">
            <thead>
		        <tr>
			        <th>Course ID</th>
			        <th>Course Name</th>
                    <th align="center">Credits</th>
			        <th>Days</th>
			        <th>Room</th>
			        <th>Instructor</th>
                    <th>Size</th>
                    <th>Enrolled</th>
		        </tr>
	        </thead>
            <tbody>
                @foreach(Course course in Model.Courses)
                {
                    <tr>
			            <td>@course.CourseName&nbsp;@course.CourseID</td>
			            <td>@course.CourseName</td>
                        <td align="center">@course.Credits</td>
			            <td>@Html.Raw(string.Join("<br/>", course.Sections[0].Days.ToArray()))</td>
			            <td>@Html.Raw(string.Join("<br/>", course.Sections[0].Room.ToArray()))</td>
			            <td>@Html.Raw(string.Join("<br/>", course.Sections[0].Instructor.ToArray()))</td>
                        <td>@course.Sections[0].Size</td>
                        <td>@course.Sections[0].Enrolled</td>
		            </tr>
                }@*
		        
		        <tr class="even gradeC">
			        <td>Trident</td>
			        <td>Internet
				         Explorer 5.0</td>
			        <td>Win 95+</td>
			        <td class="center">5</td>
			        <td class="center">C</td>
		        </tr>*@
            </tbody>
        </table>
        @*<a class="btn" href="#"><i class="icon-cog"></i> Default</a>*@
    }
</section>

WebApp/Views/Labs/LabMain.cshtml
@{
    ViewBag.Title = "Lab Main";
}

<h1>Lab Work</h1>
<h5>@Html.ActionLink("Lab 3 - AJAX & Java Script", "Lab3", "Labs")</h5>
<h5>@Html.ActionLink("Lab 4 - Server Side", "Lab4", "Labs")</h5>
<h5>@Html.ActionLink("Lab 5 – Pulling Stock Data", "Lab5", "Labs")</h5>
<h5>@Html.ActionLink("Lab 6 – Cascading Style Sheets", "Lab6", "Labs")</h5>
<h5>@Html.ActionLink("Lab 7 – POSTed Course Listings", "Lab7", "Labs")</h5>

WebApp/Views/Labs/_ModulusSumPartial.cshtml
@model WebApp.Models.LabModels

@if(Model != null && Model.ModulusSum > 0)
{
	List<string> digits = Model.UserID.Select(digit => digit.ToString()).ToList();
	int numOfDigits = digits.Count;
	int count = 0;
	
	<section class="social" id="socialLoginForm">
		<h2>Here is the solution</h2>
		
		@foreach(string num in digits)
		{
			count++;
	  
			if(count < numOfDigits)
			{ 
				@String.Format("{0} + ", num)
			}
			else
			{ 
				@String.Format("{0} = {1}", num, Model.DigitSum)
			}
		}
		
		<br />
		<br />
		Modulus Result: @Model.ModulusSum (@Model.DigitSum % 100)
	</section>
}

WebApp/Views/Labs/_PrintingCalculatorPartial.cshtml
@model WebApp.ViewModels.Lab4ViewModel

<section class="social" id="socialLoginForm">
    @if(Model != null && Model.RunningCalculations != null && Model.RunningCalculations.Count > 0)
    {	
		<span>Session will expire at: @Model.SessionTimeOut</span>
        <h2>Running Total</h2>
        <table>        
		@foreach(string op in Model.RunningCalculations)
        {
            <tr>
                <td style="width: 100px; text-align:right;">@op</td>
            </tr>
        }
            <tr>
                <td style="width: 100px; text-align:right;">
                    <span>------------</span><br />
                    @Model.RunningTotal<br />
                    <span>------------</span><br />
                </td>
            </tr>
        </table>	
    }

    @if(!string.IsNullOrEmpty(Request.Params["clearmemory"]) && Request.Params["clearmemory"] == "C")
    {
        <h2>Session Data Cleared</h2>
    }
</section>

WebApp/Views/Labs/_StockSummaryPartial.cshtml
<div class="rtq_leaf">
    <div class="rtq_div">
        <div class="yui-g">
            <div class="yfi_rt_quote_summary">
                <div class="hd">
                    <div class="title">
                        <h2>Stock symbol not found</h2>                        
                    </div>
                </div>
                <div class="yfi_rt_quote_summary_rt_top">
                    <p>
                       To get a quote, enter a stock symbol in the quote box above.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>